### ISSUE TITLE
No jokes found for german language

### ISSUE THREAD

**Issue by noah-be** [MycroftAI/skill-joke#22]
Hello, first I want to thank you for writing this skill. I use the skill with german language and have the problem that the pyjoke library returns no jokes found for this language. I read in the last issue with the german language that the skill trys to translate a joke if there is no joke for a language but in my case there is no translation. If I change the language (not in the mycroft config but in the line where it is used in the skill) to english it works but the english jokes are pronounced in german. I am not sure if this is how it should work or if there is a problem. Anyway thank you for your work!

Edit: The skills tells me "no jokes found" (in english with correct pronounciation) if I use it with german language

**Comment by krisgesling** [comment]
Hey there, glad you're enjoying it and thanks for flagging this. It does sound like a little bug. 

Have tagged with `help wanted` as it seems like a good issue for a newer developer.
